//! `src`のmodule境界を検査する。
//!
//! ファイル名と公開する責務を一致させるため、Rust sourceをASTとして読み、top-levelで
//! 非privateなitemを1つに制限する。公開関数を置くファイルは、関数名とfile stemも一致
//! させる。`mod.rs`はmoduleの入口なので名前の一致は求めないが、実装itemを置かず、
//! moduleの組み立てとre-exportに限定するため、同じ1公開itemの規則を適用する。
//!
//! 境界はcoverageの母集団も決める。`#[cfg(test)]`でしか組み立たないmoduleは本番codeでは
//! ないため、coverageが数えるpathへ置かない。置き場所の規約と、coverageが実際に外すpath
//! が食い違うと、test支援codeの高いcoverageが本番codeの不足を相殺する。

use std::fs;
use std::path::{Path, PathBuf};

use syn::{File, Item, Visibility};

struct Source {
    relative: String,
    path: PathBuf,
    syntax: File,
}

#[derive(Debug)]
struct Export {
    name: String,
    expected_stem: String,
    reexport: bool,
}

#[test]
fn source_files_have_one_named_public_subject() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();

    let mut violations = Vec::new();
    for path in paths {
        let relative = relative_to(root, &path)?;
        let text = fs::read_to_string(&path)?;
        let syntax = syn::parse_file(&text)?;
        let source = Source {
            relative,
            path,
            syntax,
        };
        check_source(&source, &mut violations);
    }

    assert!(
        violations.is_empty(),
        "source files violate the one-public-subject rule:\n{}",
        violations.join("\n")
    );
    Ok(())
}

fn collect_sources(
    directory: &Path,
    found: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_sources(&path, found)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            found.push(path);
        }
    }
    Ok(())
}

fn check_source(source: &Source, violations: &mut Vec<String>) {
    let exports = public_items(&source.syntax);
    let is_module = file_stem(&source.path) == "mod";
    if is_module {
        let implementations: Vec<String> = source
            .syntax
            .items
            .iter()
            .filter(|item| !matches!(item, Item::Mod(_) | Item::Use(_)))
            .map(item_name)
            .collect();
        if !implementations.is_empty() {
            violations.push(format!(
                "{}: mod.rs may contain only module declarations and use items; found {}",
                source.relative,
                implementations.join(", ")
            ));
        }
        return;
    }

    if exports.len() > 1 {
        let names = if exports.is_empty() {
            "no public subject".to_string()
        } else {
            exports
                .iter()
                .map(|export| export.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };
        violations.push(format!(
            "{}: expected one public subject, found {names}",
            source.relative
        ));
        return;
    }

    if exports.is_empty() {
        return;
    }

    let export = &exports[0];
    if !export.reexport && export.expected_stem.is_empty() {
        violations.push(format!(
            "{}: public subjects generated by macro `{}` must be listed explicitly",
            source.relative, export.name
        ));
    } else if export.reexport {
        violations.push(format!(
            "{}: public re-exports belong in mod.rs",
            source.relative
        ));
    } else if file_stem(&source.path) != export.expected_stem {
        violations.push(format!(
            "{}: `{}` belongs in {}.rs",
            source.relative, export.name, export.expected_stem
        ));
    }
}

fn public_items(file: &File) -> Vec<Export> {
    file.items
        .iter()
        .filter_map(|item| match item {
            Item::Const(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Enum(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::ExternCrate(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Fn(item) if visible(&item.vis) => Some(Export {
                name: item.sig.ident.to_string(),
                expected_stem: item.sig.ident.to_string(),
                reexport: false,
            }),
            Item::Mod(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Static(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Struct(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Trait(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::TraitAlias(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Type(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Union(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Use(item) if visible(&item.vis) => Some(Export {
                name: "pub use".to_string(),
                expected_stem: String::new(),
                reexport: true,
            }),
            // `syn` does not expand macros. The one macro that deliberately emits a public
            // subject is recognized here; every other top-level invocation is reported rather
            // than silently disappearing from the subject count.
            // A `macro_rules!` declaration only defines an invocation; it emits no subject by
            // itself.
            Item::Macro(item) if item.mac.path.is_ident("macro_rules") => None,
            Item::Macro(item) if item.ident.is_none() && item.mac.path.is_ident("error_ids") => {
                Some(Export {
                    name: "ErrorId".to_string(),
                    expected_stem: "error_id".to_string(),
                    reexport: false,
                })
            }
            Item::Macro(item) if item.ident.is_none() => Some(Export {
                name: macro_name(item),
                expected_stem: String::new(),
                reexport: false,
            }),
            _ => None,
        })
        .collect()
}

fn macro_name(item: &syn::ItemMacro) -> String {
    item.mac.path.segments.last().map_or_else(
        || "unknown".to_string(),
        |segment| segment.ident.to_string(),
    )
}

fn visible(visibility: &Visibility) -> bool {
    !matches!(visibility, Visibility::Inherited)
}

fn item_name(item: &Item) -> String {
    match item {
        Item::Const(item) => format!("const {}", item.ident),
        Item::Enum(item) => format!("enum {}", item.ident),
        Item::ExternCrate(item) => format!("extern crate {}", item.ident),
        Item::Fn(item) => format!("fn {}", item.sig.ident),
        Item::ForeignMod(_) => "extern block".to_string(),
        Item::Impl(_) => "impl block".to_string(),
        Item::Macro(_) => "macro".to_string(),
        Item::Mod(item) => format!("mod {}", item.ident),
        Item::Static(item) => format!("static {}", item.ident),
        Item::Struct(item) => format!("struct {}", item.ident),
        Item::Trait(item) => format!("trait {}", item.ident),
        Item::TraitAlias(item) => format!("trait alias {}", item.ident),
        Item::Type(item) => format!("type {}", item.ident),
        Item::Union(item) => format!("union {}", item.ident),
        Item::Use(_) => "use".to_string(),
        Item::Verbatim(_) => "verbatim item".to_string(),
        _ => "item".to_string(),
    }
}

fn file_stem(path: &Path) -> &str {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("")
}

fn relative_to(root: &Path, path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    Ok(path
        .strip_prefix(root)
        .map_err(|error| format!("{} is outside the repository: {error}", path.display()))?
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/"))
}

/// coverageが数えない置き場所の規約。
///
/// `mise.toml`の`--ignore-filename-regex`が同じ規約を綴る。左が本testの判定、右が
/// coverage taskへ渡す正規表現の一部であり、両方を書き換えなければ規約は動かせない。
const OUTSIDE_THE_COVERAGE_POPULATION: [(&str, &str); 4] = [
    ("tests/", "(^|/)tests/"),
    ("src/testing/", "(^|/)src/testing/"),
    ("fake/", "(^|/)fake/"),
    ("_test", "[^/]*_test[^/]*\\.rs$"),
];

/// coverageが数えないpathか。
///
/// `src`を歩く本testはrepository rootの`tests/`へ到達しないため、残る3つだけを見る。
fn outside_the_coverage_population(relative: &str) -> bool {
    let name = relative.rsplit('/').next().unwrap_or(relative);
    relative.starts_with("src/testing/") || relative.contains("/fake/") || name.contains("_test")
}

/// `#[cfg(test)]`が付いているか。
fn gated_by_test(attributes: &[syn::Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        attribute.path().is_ident("cfg")
            && attribute
                .parse_args::<syn::Path>()
                .is_ok_and(|path| path.is_ident("test"))
    })
}

/// `#[path = "..."]`が指すfile名。
fn path_attribute(declaration: &syn::ItemMod) -> Option<String> {
    declaration.attrs.iter().find_map(|attribute| {
        let syn::Meta::NameValue(meta) = &attribute.meta else {
            return None;
        };
        if !meta.path.is_ident("path") {
            return None;
        }
        let syn::Expr::Lit(expression) = &meta.value else {
            return None;
        };
        let syn::Lit::Str(literal) = &expression.lit else {
            return None;
        };
        Some(literal.value())
    })
}

/// module宣言が読み込むfile。
///
/// `#[path]`はそれを書いたfileのdirectoryから解決する。`#[path]`が無い場合、`mod.rs`と
/// crate rootは同じdirectory、それ以外のfileはfile stemと同じ名前のdirectoryを探す。
fn declared_file(declaring: &Path, declaration: &syn::ItemMod) -> Option<PathBuf> {
    // 中身を持つmoduleは、宣言したfileそのものへ置かれる。
    if declaration.content.is_some() {
        return Some(declaring.to_path_buf());
    }
    let directory = declaring.parent()?;
    if let Some(named) = path_attribute(declaration) {
        return Some(directory.join(named));
    }
    let stem = file_stem(declaring);
    let module_directory = if stem == "mod" || stem == "main" {
        directory.to_path_buf()
    } else {
        directory.join(stem)
    };
    let name = declaration.ident.to_string();
    let file = module_directory.join(format!("{name}.rs"));
    if file.is_file() {
        return Some(file);
    }
    Some(module_directory.join(name).join("mod.rs"))
}

#[test]
fn test_only_modules_are_outside_the_coverage_population() -> Result<(), Box<dyn std::error::Error>>
{
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();

    let mut violations = Vec::new();
    for path in paths {
        let text = fs::read_to_string(&path)?;
        let syntax = syn::parse_file(&text)?;
        for item in &syntax.items {
            let Item::Mod(declaration) = item else {
                continue;
            };
            if !gated_by_test(&declaration.attrs) {
                continue;
            }
            let declared = declared_file(&path, declaration)
                .ok_or_else(|| format!("{}: the module has no directory", path.display()))?;
            let declared = relative_to(root, &declared)?;
            if !outside_the_coverage_population(&declared) {
                violations.push(format!(
                    "{}: `{}` builds only for tests, but {declared} is counted",
                    relative_to(root, &path)?,
                    declaration.ident
                ));
            }
        }
    }

    let places = OUTSIDE_THE_COVERAGE_POPULATION
        .map(|(place, _)| place)
        .join(", ");
    assert!(
        violations.is_empty(),
        "test support belongs to {places}:\n{}",
        violations.join("\n")
    );
    Ok(())
}

#[test]
fn the_coverage_task_leaves_out_the_same_places() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("mise.toml"))?;
    let declared = manifest
        .lines()
        .find(|line| line.contains("--ignore-filename-regex"))
        .ok_or("mise.toml leaves out no path from coverage")?;

    let mut missing = Vec::new();
    for (place, pattern) in OUTSIDE_THE_COVERAGE_POPULATION {
        if !declared.contains(pattern) {
            missing.push(format!("{place} ({pattern})"));
        }
    }

    assert!(
        missing.is_empty(),
        "the coverage task must leave out every place test support may live; missing {}",
        missing.join(", ")
    );
    Ok(())
}

/// item名をfile stemへ写す。
///
/// `CamelCase`と`SCREAMING_SNAKE_CASE`の両方を同じ規則で扱う。語の境界は、小文字か
/// 数字のあとの大文字と、大文字が続いたあとに小文字が始まる位置だけとする。既にある
/// `_`は境界そのものなので、そこへ重ねて`_`を足さない。
fn snake_case(name: &str) -> String {
    let characters: Vec<char> = name.chars().collect();
    let mut result = String::with_capacity(name.len());
    for (index, &character) in characters.iter().enumerate() {
        if character == '_' {
            result.push('_');
            continue;
        }
        let previous = index.checked_sub(1).map(|before| characters[before]);
        let boundary = character.is_ascii_uppercase()
            && match previous {
                None | Some('_') => false,
                // 略語の途中は切らない。`SSH_CLONE`は`ssh_clone`、`ProjectId`は`project_id`。
                Some(before) if before.is_ascii_uppercase() => characters
                    .get(index + 1)
                    .is_some_and(char::is_ascii_lowercase),
                Some(_) => true,
            };
        if boundary {
            result.push('_');
        }
        result.push(character.to_ascii_lowercase());
    }
    result
}

#[test]
fn a_known_macro_subject_is_counted() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! error_ids {
            () => { pub enum ErrorId { One } };
        }
        error_ids! {}
        ",
    )?;
    let source = Source {
        relative: "src/error_id.rs".to_string(),
        path: PathBuf::from("error_id.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert!(
        violations.is_empty(),
        "unexpected violations: {violations:?}"
    );
    Ok(())
}

#[test]
fn a_macro_subject_cannot_hide_another_public_subject() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! error_ids {
            () => { pub enum ErrorId { One } };
        }
        error_ids! {}
        pub fn error_id() {}
        ",
    )?;
    let source = Source {
        relative: "src/error_id.rs".to_string(),
        path: PathBuf::from("error_id.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert_eq!(violations.len(), 1);
    assert!(violations[0].contains("ErrorId, error_id"));
    Ok(())
}

#[test]
fn an_unknown_public_macro_is_not_silently_ignored() -> Result<(), syn::Error> {
    let syntax = syn::parse_file("make_public!();")?;
    let source = Source {
        relative: "src/make_public.rs".to_string(),
        path: PathBuf::from("make_public.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert_eq!(violations.len(), 1);
    assert!(violations[0].contains("make_public"));
    Ok(())
}
