//! `src`のmodule境界を検査する。
//!
//! ファイル名と公開する責務を一致させるため、Rust sourceをASTとして読み、top-levelで
//! 非privateなitemを1つに制限する。公開関数を置くファイルは、関数名とfile stemも一致
//! させる。`mod.rs`はmoduleの入口なので名前の一致は求めないが、実装itemを置かず、
//! moduleの組み立てとre-exportに限定するため、同じ1公開itemの規則を適用する。
//!
//! 境界はcoverageの母集団も決める。`#[cfg(test)]`でしか組み立たないcodeは本番codeでは
//! ないため、coverageが数えるpathへ置かない。置き場所の規約と、coverageが実際に外すpath
//! が食い違うと、test支援codeの高いcoverageが本番codeの不足を相殺する。
//!
//! llvm-covはfile単位でしか母集団を外せない。moduleだけでなくitemも同じ規約に従わせ、
//! 母集団は両方向から固定する。数えるfileにtest支援codeが混じることも、除外を足して
//! 本番codeを母集団から外すことも、どちらも落とす。

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::fs;
use std::path::{Path, PathBuf};

use proc_macro2::{Delimiter, TokenTree};
use syn::visit::Visit;
use syn::{Expr, File, Item, Visibility};

struct Source {
    relative: String,
    path: PathBuf,
    syntax: File,
}

#[derive(Debug)]
struct Export {
    name: String,
    expected_stem: String,
    reexport: bool,
}

#[test]
fn source_files_have_one_named_public_subject() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();

    let mut violations = Vec::new();
    for path in paths {
        let relative = relative_to(root, &path)?;
        let text = fs::read_to_string(&path)?;
        let syntax = syn::parse_file(&text)?;
        let source = Source {
            relative,
            path,
            syntax,
        };
        check_source(&source, &mut violations);
    }

    assert!(
        violations.is_empty(),
        "source files violate the one-public-subject rule:\n{}",
        violations.join("\n")
    );
    Ok(())
}

fn collect_sources(
    directory: &Path,
    found: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_sources(&path, found)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            found.push(path);
        }
    }
    Ok(())
}

fn check_source(source: &Source, violations: &mut Vec<String>) {
    let exports = public_items(&source.syntax);
    let is_module = file_stem(&source.path) == "mod";
    if is_module {
        let implementations: Vec<String> = source
            .syntax
            .items
            .iter()
            .filter(|item| !matches!(item, Item::Mod(_) | Item::Use(_)))
            .map(item_name)
            .collect();
        if !implementations.is_empty() {
            violations.push(format!(
                "{}: mod.rs may contain only module declarations and use items; found {}",
                source.relative,
                implementations.join(", ")
            ));
        }
        return;
    }

    if exports.len() > 1 {
        let names = if exports.is_empty() {
            "no public subject".to_string()
        } else {
            exports
                .iter()
                .map(|export| export.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        };
        violations.push(format!(
            "{}: expected one public subject, found {names}",
            source.relative
        ));
        return;
    }

    if exports.is_empty() {
        return;
    }

    let export = &exports[0];
    if !export.reexport && export.expected_stem.is_empty() {
        violations.push(format!(
            "{}: public subjects generated by macro `{}` must be listed explicitly",
            source.relative, export.name
        ));
    } else if export.reexport {
        violations.push(format!(
            "{}: public re-exports belong in mod.rs",
            source.relative
        ));
    } else if file_stem(&source.path) != export.expected_stem {
        violations.push(format!(
            "{}: `{}` belongs in {}.rs",
            source.relative, export.name, export.expected_stem
        ));
    }
}

fn public_items(file: &File) -> Vec<Export> {
    file.items
        .iter()
        .filter_map(|item| match item {
            Item::Const(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Enum(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::ExternCrate(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Fn(item) if visible(&item.vis) => Some(Export {
                name: item.sig.ident.to_string(),
                expected_stem: item.sig.ident.to_string(),
                reexport: false,
            }),
            Item::Mod(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Static(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Struct(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Trait(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::TraitAlias(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Type(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Union(item) if visible(&item.vis) => Some(Export {
                name: item.ident.to_string(),
                expected_stem: snake_case(&item.ident.to_string()),
                reexport: false,
            }),
            Item::Use(item) if visible(&item.vis) => Some(Export {
                name: "pub use".to_string(),
                expected_stem: String::new(),
                reexport: true,
            }),
            // `syn` does not expand macros. The one macro that deliberately emits a public
            // subject is recognized here; every other top-level invocation is reported rather
            // than silently disappearing from the subject count.
            // A `macro_rules!` declaration only defines an invocation; it emits no subject by
            // itself.
            Item::Macro(item) if item.mac.path.is_ident("macro_rules") => None,
            Item::Macro(item) if item.ident.is_none() && item.mac.path.is_ident("error_ids") => {
                Some(Export {
                    name: "ErrorId".to_string(),
                    expected_stem: "error_id".to_string(),
                    reexport: false,
                })
            }
            Item::Macro(item) if item.ident.is_none() => Some(Export {
                name: macro_name(item),
                expected_stem: String::new(),
                reexport: false,
            }),
            _ => None,
        })
        .collect()
}

fn macro_name(item: &syn::ItemMacro) -> String {
    item.mac.path.segments.last().map_or_else(
        || "unknown".to_string(),
        |segment| segment.ident.to_string(),
    )
}

fn visible(visibility: &Visibility) -> bool {
    !matches!(visibility, Visibility::Inherited)
}

fn item_name(item: &Item) -> String {
    match item {
        Item::Const(item) => format!("const {}", item.ident),
        Item::Enum(item) => format!("enum {}", item.ident),
        Item::ExternCrate(item) => format!("extern crate {}", item.ident),
        Item::Fn(item) => format!("fn {}", item.sig.ident),
        Item::ForeignMod(_) => "extern block".to_string(),
        Item::Impl(_) => "impl block".to_string(),
        Item::Macro(_) => "macro".to_string(),
        Item::Mod(item) => format!("mod {}", item.ident),
        Item::Static(item) => format!("static {}", item.ident),
        Item::Struct(item) => format!("struct {}", item.ident),
        Item::Trait(item) => format!("trait {}", item.ident),
        Item::TraitAlias(item) => format!("trait alias {}", item.ident),
        Item::Type(item) => format!("type {}", item.ident),
        Item::Union(item) => format!("union {}", item.ident),
        Item::Use(_) => "use".to_string(),
        Item::Verbatim(_) => "verbatim item".to_string(),
        _ => "item".to_string(),
    }
}

fn file_stem(path: &Path) -> &str {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("")
}

fn relative_to(root: &Path, path: &Path) -> Result<String, Box<dyn std::error::Error>> {
    Ok(path
        .strip_prefix(root)
        .map_err(|error| format!("{} is outside the repository: {error}", path.display()))?
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/"))
}

/// coverageが数えない置き場所の規約。
///
/// `mise.toml`の`--ignore-filename-regex`が同じ規約を綴る。左が本testの判定、右が
/// coverage taskへ渡す正規表現の一部であり、両方を書き換えなければ規約は動かせない。
const OUTSIDE_THE_COVERAGE_POPULATION: [(&str, &str); 4] = [
    ("tests/", "(^|/)tests/"),
    ("src/testing/", "(^|/)src/testing/"),
    ("fake/", "(^|/)fake/"),
    ("_test", "[^/]*_test[^/]*\\.rs$"),
];

/// coverageが数えないpathか。
///
/// 上の表の左側を、正規表現と同じ順で綴る。
fn outside_the_coverage_population(relative: &str) -> bool {
    let name = relative.rsplit('/').next().unwrap_or(relative);
    on_the_path(relative, "tests/")
        || on_the_path(relative, "src/testing/")
        || on_the_path(relative, "fake/")
        || name.contains("_test")
}

/// pathがその区切りから始まるか、途中にその区切りを含むか。`(^|/)`と同じ判定。
fn on_the_path(relative: &str, place: &str) -> bool {
    relative.starts_with(place) || relative.contains(&format!("/{place}"))
}

/// cfg predicateの真偽。
///
/// `test`以外のatomは、同じsourceでもtargetや環境によって両方の値を取る。判定できない
/// ことを`Unknown`として残し、綴りではなく意味でitemの有無を決める。
#[derive(Clone, Copy, PartialEq, Eq)]
enum Truth {
    Yes,
    No,
    Unknown,
}

fn not(value: Truth) -> Truth {
    match value {
        Truth::Yes => Truth::No,
        Truth::No => Truth::Yes,
        Truth::Unknown => Truth::Unknown,
    }
}

fn and(left: Truth, right: Truth) -> Truth {
    match (left, right) {
        (Truth::No, _) | (_, Truth::No) => Truth::No,
        (Truth::Unknown, _) | (_, Truth::Unknown) => Truth::Unknown,
        (Truth::Yes, Truth::Yes) => Truth::Yes,
    }
}

fn or(left: Truth, right: Truth) -> Truth {
    match (left, right) {
        (Truth::Yes, _) | (_, Truth::Yes) => Truth::Yes,
        (Truth::Unknown, _) | (_, Truth::Unknown) => Truth::Unknown,
        (Truth::No, Truth::No) => Truth::No,
    }
}

/// `test`をこの値へ固定してcfg predicateを評価する。
fn evaluate(predicate: &syn::Meta, test: bool) -> Truth {
    match predicate {
        syn::Meta::Path(path) if path.is_ident("test") => {
            if test {
                Truth::Yes
            } else {
                Truth::No
            }
        }
        // `unix`や`target_os = "macos"`など、test buildかどうかとは無関係のatom。
        syn::Meta::Path(_) | syn::Meta::NameValue(_) => Truth::Unknown,
        syn::Meta::List(list) => {
            let Ok(inner) = list.parse_args_with(
                syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
            ) else {
                return Truth::Unknown;
            };
            let values = inner.iter().map(|meta| evaluate(meta, test));
            if list.path.is_ident("not") {
                values.map(not).fold(Truth::Yes, and)
            } else if list.path.is_ident("all") {
                values.fold(Truth::Yes, and)
            } else if list.path.is_ident("any") {
                values.fold(Truth::No, or)
            } else {
                Truth::Unknown
            }
        }
    }
}

/// itemがどのbuildに存在するか。
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Gate {
    /// cfgが無いか、cfgが`test`を見ない。どちらのbuildにも同じように存在する。
    Unconditional,
    /// test buildでしか存在しない。
    TestOnly,
    /// 本番buildでしか存在しない。
    ProductionOnly,
    /// test buildには必ず存在し、本番buildにも別の条件しだいで存在する。
    Undecidable,
}

/// itemに付いた`#[cfg]`から、そのitemが存在するbuildを決める。
///
/// 同じitemへ複数の`#[cfg]`を付けるとrustcはANDとして扱うため、ここでも畳み込む。
fn gate(attributes: &[syn::Attribute]) -> Gate {
    let mut in_test = Truth::Yes;
    let mut in_production = Truth::Yes;
    for attribute in attributes.iter().filter(|a| a.path().is_ident("cfg")) {
        let Ok(predicate) = attribute.parse_args::<syn::Meta>() else {
            continue;
        };
        in_test = and(in_test, evaluate(&predicate, true));
        in_production = and(in_production, evaluate(&predicate, false));
    }
    if in_production == Truth::No {
        Gate::TestOnly
    } else if in_test == Truth::No {
        Gate::ProductionOnly
    } else if in_test == in_production {
        Gate::Unconditional
    } else {
        Gate::Undecidable
    }
}

/// `#[cfg_attr]`がtest buildでだけ属性を足すか。
///
/// itemそのものは両方のbuildに存在しても、test buildでだけ`derive`が増えれば、そこで
/// 生まれるimplはtestしか持たないcodeである。
fn attribute_follows_the_test_build(attribute: &syn::Attribute) -> bool {
    if !attribute.path().is_ident("cfg_attr") {
        return false;
    }
    let Ok(arguments) = attribute.parse_args_with(
        syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
    ) else {
        return false;
    };
    arguments
        .first()
        .is_some_and(|predicate| evaluate(predicate, true) != evaluate(predicate, false))
}

/// `#[path = "..."]`が指すfile名。
fn path_attribute(declaration: &syn::ItemMod) -> Option<String> {
    declaration.attrs.iter().find_map(|attribute| {
        let syn::Meta::NameValue(meta) = &attribute.meta else {
            return None;
        };
        if !meta.path.is_ident("path") {
            return None;
        }
        let syn::Expr::Lit(expression) = &meta.value else {
            return None;
        };
        let syn::Lit::Str(literal) = &expression.lit else {
            return None;
        };
        Some(literal.value())
    })
}

/// module宣言が読み込むfile。
///
/// `#[path]`はそれを書いたfileのdirectoryから解決する。`#[path]`が無い場合、`mod.rs`と
/// crate rootは同じdirectory、それ以外のfileはfile stemと同じ名前のdirectoryを探す。
fn declared_file(declaring: &Path, declaration: &syn::ItemMod) -> Option<PathBuf> {
    // 中身を持つmoduleは、宣言したfileそのものへ置かれる。
    if declaration.content.is_some() {
        return Some(declaring.to_path_buf());
    }
    let directory = declaring.parent()?;
    if let Some(named) = path_attribute(declaration) {
        return Some(directory.join(named));
    }
    let stem = file_stem(declaring);
    let module_directory = if stem == "mod" || stem == "main" {
        directory.to_path_buf()
    } else {
        directory.join(stem)
    };
    let name = declaration.ident.to_string();
    let file = module_directory.join(format!("{name}.rs"));
    if file.is_file() {
        return Some(file);
    }
    Some(module_directory.join(name).join("mod.rs"))
}

/// fileが宣言するmodule。
///
/// 中身を持つmoduleは自身のfileへ残るため、その中の宣言まで降りる。囲むmoduleが
/// test buildのものなら、中の宣言も同じbuildのものである。
fn module_declarations<'a>(
    items: &'a [Item],
    gated: bool,
    found: &mut Vec<(&'a syn::ItemMod, bool)>,
) {
    for item in items {
        let Item::Mod(declaration) = item else {
            continue;
        };
        let gated = gated || gate(&declaration.attrs) == Gate::TestOnly;
        match &declaration.content {
            Some((_, inner)) => module_declarations(inner, gated, found),
            None => found.push((declaration, gated)),
        }
    }
}

/// coverageが数えるfileへ、test buildでしか組み立たないcodeを置いていないか。
///
/// llvm-covはfile単位でしか母集団を外せない。同じfileの中へ`#[cfg(test)]`のitemや
/// statementを書くと、そのcodeはtestが必ず踏むため、本番codeの不足をそのまま相殺する。
/// `use`とmodule宣言はitemであってもcodeを生まないため、置き場所を指すためだけに残す。
#[test]
fn test_only_items_are_outside_the_coverage_population() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();

    let mut violations = Vec::new();
    for path in paths {
        let relative = relative_to(root, &path)?;
        if outside_the_coverage_population(&relative) {
            continue;
        }
        let syntax = syn::parse_file(&fs::read_to_string(&path)?)?;
        let mut counted = CountedFile {
            relative: &relative,
            violations: Vec::new(),
            context: "an item".to_string(),
            policy: AttributePolicy::CountedCode,
        };
        counted.visit_file(&syntax);
        violations.append(&mut counted.violations);
    }

    let places = OUTSIDE_THE_COVERAGE_POPULATION
        .map(|(place, _)| place)
        .join(", ");
    assert!(
        violations.is_empty(),
        "test support belongs to {places}:\n{}",
        violations.join("\n")
    );
    Ok(())
}

/// coverageが数えるfileの中で、test buildだけのcodeを集める。
struct CountedFile<'a> {
    relative: &'a str,
    violations: Vec<String>,
    context: String,
    policy: AttributePolicy,
}

/// test専用の条件を許す構文上の位置。
#[derive(Clone, Copy, PartialEq, Eq)]
enum AttributePolicy {
    /// test専用でも、本番fileに置いてよい。module宣言やuseが該当する。
    AllowTestOnly,
    /// test専用のcodeを置いてはいけない。
    CountedCode,
}

impl CountedFile<'_> {
    /// 属性1つを、現在の構文上の位置に対して検査する。
    fn check_attribute(&mut self, attribute: &syn::Attribute) {
        let attributes = std::slice::from_ref(attribute);
        if gate(attributes) == Gate::TestOnly && self.policy == AttributePolicy::CountedCode {
            self.violations.push(format!(
                "{}: {} builds only for tests; move it beside its subject in a _test file",
                self.relative, self.context
            ));
        }
        if attribute_follows_the_test_build(attribute) {
            self.violations.push(format!(
                "{}: {} takes an attribute only in test builds",
                self.relative, self.context
            ));
        }
    }

    fn check_macro(&mut self, invocation: &syn::Macro) {
        if macro_has_test_condition(invocation) {
            self.violations.push(format!(
                "{}: {} macro has a condition that depends on `test`",
                self.relative, self.context
            ));
        }
    }
}

impl<'ast> Visit<'ast> for CountedFile<'_> {
    fn visit_item(&mut self, item: &'ast Item) {
        // module宣言は置き場所を指すだけで、codeはその先のfileにある。指した先が母集団の
        // 外かどうかは、crate rootから辿るtestが見る。
        let policy = match item {
            Item::Mod(declaration) => declaration.content.is_none(),
            Item::Use(_) | Item::ExternCrate(_) => true,
            _ => false,
        };
        let policy = if policy {
            AttributePolicy::AllowTestOnly
        } else {
            AttributePolicy::CountedCode
        };
        let item_context = match item {
            Item::Macro(item) => format!("macro `{}`", macro_display_name(item)),
            _ => item_name(item),
        };
        let previous_context = std::mem::replace(&mut self.context, item_context);
        let previous_policy = std::mem::replace(&mut self.policy, policy);
        if let Item::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_item(self, item);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_impl_item(&mut self, item: &'ast syn::ImplItem) {
        let previous_context =
            std::mem::replace(&mut self.context, "an associated item".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        if let syn::ImplItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_impl_item(self, item);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_trait_item(&mut self, item: &'ast syn::TraitItem) {
        let previous_context = std::mem::replace(&mut self.context, "a trait item".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        if let syn::TraitItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_trait_item(self, item);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_foreign_item(&mut self, item: &'ast syn::ForeignItem) {
        let previous_context = std::mem::replace(&mut self.context, "an extern item".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        if let syn::ForeignItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_foreign_item(self, item);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_variant(&mut self, variant: &'ast syn::Variant) {
        let previous_context = std::mem::replace(&mut self.context, "an enum variant".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        syn::visit::visit_variant(self, variant);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_field(&mut self, field: &'ast syn::Field) {
        let previous_context = std::mem::replace(&mut self.context, "a field".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        syn::visit::visit_field(self, field);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_local(&mut self, local: &'ast syn::Local) {
        let previous_context = std::mem::replace(&mut self.context, "a binding".to_string());
        let previous_policy = std::mem::replace(&mut self.policy, AttributePolicy::CountedCode);
        syn::visit::visit_local(self, local);
        self.context = previous_context;
        self.policy = previous_policy;
    }

    fn visit_attribute(&mut self, attribute: &'ast syn::Attribute) {
        self.check_attribute(attribute);
    }

    fn visit_stmt_macro(&mut self, statement: &'ast syn::StmtMacro) {
        let previous_context =
            std::mem::replace(&mut self.context, "a statement macro".to_string());
        self.check_macro(&statement.mac);
        syn::visit::visit_stmt_macro(self, statement);
        self.context = previous_context;
    }

    fn visit_expr(&mut self, expression: &'ast Expr) {
        if let Expr::Macro(expression) = expression {
            let previous_context =
                std::mem::replace(&mut self.context, "an expression macro".to_string());
            self.check_macro(&expression.mac);
            self.context = previous_context;
        }
        syn::visit::visit_expr(self, expression);
    }
}

/// macro bodyに`test`で変わる`cfg`または`cfg_attr`があるか。
///
/// `syn`はmacroを展開しないため、token treeの属性だけを取り出してpredicateを評価する。
/// predicateが構文上解釈できない場合も、test条件を隠せるため安全側に倒して落とす。
fn macro_has_test_condition(invocation: &syn::Macro) -> bool {
    token_stream_has_test_condition(invocation.tokens.clone())
}

fn macro_display_name(item: &syn::ItemMacro) -> String {
    item.ident
        .as_ref()
        .map_or_else(|| macro_name(item), std::string::ToString::to_string)
}

fn token_stream_has_test_condition(tokens: proc_macro2::TokenStream) -> bool {
    let tokens: Vec<TokenTree> = tokens.into_iter().collect();
    let mut index = 0;
    while index < tokens.len() {
        if matches!(&tokens[index], TokenTree::Punct(punct) if punct.as_char() == '#')
            && let Some(TokenTree::Group(group)) = tokens.get(index + 1)
            && group.delimiter() == Delimiter::Bracket
            && attribute_meta_has_test_condition(&group.stream())
        {
            return true;
        }

        if let TokenTree::Group(group) = &tokens[index]
            && token_stream_has_test_condition(group.stream())
        {
            return true;
        }
        index += 1;
    }
    false
}

fn attribute_meta_has_test_condition(tokens: &proc_macro2::TokenStream) -> bool {
    let Ok(meta) = syn::parse2::<syn::Meta>(tokens.clone()) else {
        return false;
    };
    let syn::Meta::List(list) = &meta else {
        return false;
    };
    if list.path.is_ident("cfg") {
        let Ok(predicate) = list.parse_args::<syn::Meta>() else {
            return true;
        };
        return evaluate(&predicate, true) != evaluate(&predicate, false);
    }
    if list.path.is_ident("cfg_attr") {
        let Ok(arguments) = list.parse_args_with(
            syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated,
        ) else {
            return true;
        };
        return arguments
            .first()
            .is_some_and(|predicate| evaluate(predicate, true) != evaluate(predicate, false));
    }
    false
}

fn item_attributes(item: &Item) -> &[syn::Attribute] {
    match item {
        Item::Const(item) => &item.attrs,
        Item::Enum(item) => &item.attrs,
        Item::ExternCrate(item) => &item.attrs,
        Item::Fn(item) => &item.attrs,
        Item::ForeignMod(item) => &item.attrs,
        Item::Impl(item) => &item.attrs,
        Item::Macro(item) => &item.attrs,
        Item::Mod(item) => &item.attrs,
        Item::Static(item) => &item.attrs,
        Item::Struct(item) => &item.attrs,
        Item::Trait(item) => &item.attrs,
        Item::TraitAlias(item) => &item.attrs,
        Item::Type(item) => &item.attrs,
        Item::Union(item) => &item.attrs,
        Item::Use(item) => &item.attrs,
        _ => &[],
    }
}

/// `test`がitemとその内部のcodeの有無を1人で決めているか。
///
/// `#[cfg(not(test))]`のitemは母集団へ入るが、testからは決して踏めない。
/// `#[cfg(any(test, ...))]`のitemは、本番buildに存在するかどうかがsourceだけでは決まらず、
/// 数えるべきか外すべきかも決まらない。どちらも置かせない。
#[test]
fn the_test_build_decides_an_item_on_its_own() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();

    let mut violations = Vec::new();
    for path in paths {
        let relative = relative_to(root, &path)?;
        let syntax = syn::parse_file(&fs::read_to_string(&path)?)?;
        let mut sharing = SharedDecision {
            relative: &relative,
            violations: Vec::new(),
            context: "an item".to_string(),
        };
        sharing.visit_file(&syntax);
        violations.append(&mut sharing.violations);
    }

    assert!(
        violations.is_empty(),
        "`test` must decide an item by itself:\n{}",
        violations.join("\n")
    );
    Ok(())
}

/// `test`以外の条件と一緒にitemやその内部のcodeの有無を決めている箇所を集める。
struct SharedDecision<'a> {
    relative: &'a str,
    violations: Vec<String>,
    context: String,
}

impl<'ast> Visit<'ast> for SharedDecision<'_> {
    fn visit_item(&mut self, item: &'ast Item) {
        let item_context = match item {
            Item::Macro(item) => format!("macro `{}`", macro_display_name(item)),
            _ => item_name(item),
        };
        let previous_context = std::mem::replace(&mut self.context, item_context);
        if let Item::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_item(self, item);
        self.context = previous_context;
    }

    fn visit_impl_item(&mut self, item: &'ast syn::ImplItem) {
        let previous_context =
            std::mem::replace(&mut self.context, "an associated item".to_string());
        if let syn::ImplItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_impl_item(self, item);
        self.context = previous_context;
    }

    fn visit_trait_item(&mut self, item: &'ast syn::TraitItem) {
        let previous_context = std::mem::replace(&mut self.context, "a trait item".to_string());
        if let syn::TraitItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_trait_item(self, item);
        self.context = previous_context;
    }

    fn visit_foreign_item(&mut self, item: &'ast syn::ForeignItem) {
        let previous_context = std::mem::replace(&mut self.context, "an extern item".to_string());
        if let syn::ForeignItem::Macro(item) = item {
            self.check_macro(&item.mac);
        }
        syn::visit::visit_foreign_item(self, item);
        self.context = previous_context;
    }

    fn visit_variant(&mut self, variant: &'ast syn::Variant) {
        let previous_context = std::mem::replace(&mut self.context, "an enum variant".to_string());
        syn::visit::visit_variant(self, variant);
        self.context = previous_context;
    }

    fn visit_field(&mut self, field: &'ast syn::Field) {
        let previous_context = std::mem::replace(&mut self.context, "a field".to_string());
        syn::visit::visit_field(self, field);
        self.context = previous_context;
    }

    fn visit_local(&mut self, local: &'ast syn::Local) {
        let previous_context = std::mem::replace(&mut self.context, "a binding".to_string());
        syn::visit::visit_local(self, local);
        self.context = previous_context;
    }

    fn visit_attribute(&mut self, attribute: &'ast syn::Attribute) {
        let attributes = std::slice::from_ref(attribute);
        match gate(attributes) {
            Gate::ProductionOnly => self.violations.push(format!(
                "{}: {} is left out of the test build",
                self.relative, self.context
            )),
            Gate::Undecidable => self.violations.push(format!(
                "{}: {} shares its condition with `test`",
                self.relative, self.context
            )),
            Gate::TestOnly | Gate::Unconditional => {}
        }
        if attribute_follows_the_test_build(attribute) {
            self.violations.push(format!(
                "{}: {} takes an attribute only in test builds",
                self.relative, self.context
            ));
        }
    }

    fn visit_stmt_macro(&mut self, statement: &'ast syn::StmtMacro) {
        let previous_context =
            std::mem::replace(&mut self.context, "a statement macro".to_string());
        self.check_macro(&statement.mac);
        syn::visit::visit_stmt_macro(self, statement);
        self.context = previous_context;
    }

    fn visit_expr(&mut self, expression: &'ast Expr) {
        if let Expr::Macro(expression) = expression {
            let previous_context =
                std::mem::replace(&mut self.context, "an expression macro".to_string());
            self.check_macro(&expression.mac);
            self.context = previous_context;
        }
        syn::visit::visit_expr(self, expression);
    }
}

impl SharedDecision<'_> {
    fn check_macro(&mut self, invocation: &syn::Macro) {
        if macro_has_test_condition(invocation) {
            self.violations.push(format!(
                "{}: {} macro has a condition that depends on `test`",
                self.relative, self.context
            ));
        }
    }
}

/// coverageが数えるfileと、本番buildが組み立てるfileが一致するか。
///
/// 置き場所の規約はtest支援codeを母集団へ入れないためにある。同じ規約は、除外を足して
/// 本番codeを母集団から外すことも禁じなければならない。片側だけを見ると、`fake/`を1つ
/// 足すだけで、testの無い本番codeを数えられなくできる。
///
/// crate rootから`mod`宣言を辿り、test buildでしか組み立たないfileを求めて、規約が外す
/// fileと突き合わせる。module宣言はmodule levelにあるものだけを読む。
#[test]
fn the_coverage_population_is_what_the_crate_builds_without_tests()
-> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut violations = Vec::new();

    let mut reached: BTreeSet<(PathBuf, bool)> = BTreeSet::new();
    let mut queue: VecDeque<(PathBuf, bool)> = VecDeque::new();
    let entry = root.join("src").join("main.rs");
    reached.insert((entry.clone(), false));
    queue.push_back((entry, false));
    while let Some((file, gated)) = queue.pop_front() {
        let syntax = syn::parse_file(&fs::read_to_string(&file)?)?;
        let mut declarations = Vec::new();
        module_declarations(&syntax.items, false, &mut declarations);
        for (declaration, inner_gate) in declarations {
            let declared = declared_file(&file, declaration)
                .ok_or_else(|| format!("{}: the module has no directory", file.display()))?;
            if !declared.is_file() {
                violations.push(format!(
                    "{}: `{}` declares a file that is not there",
                    relative_to(root, &file)?,
                    declaration.ident
                ));
                continue;
            }
            let gated = gated || inner_gate || gate(&declaration.attrs) == Gate::TestOnly;
            if reached.insert((declared.clone(), gated)) {
                queue.push_back((declared, gated));
            }
        }
    }

    // 1つでも本番buildから辿れるなら、そのfileは本番codeである。
    let mut population: BTreeMap<PathBuf, bool> = BTreeMap::new();
    for (file, gated) in reached {
        population
            .entry(file)
            .and_modify(|test_only| *test_only &= gated)
            .or_insert(gated);
    }

    let mut paths = Vec::new();
    collect_sources(&root.join("src"), &mut paths)?;
    paths.sort();
    for path in paths {
        let relative = relative_to(root, &path)?;
        let counted = !outside_the_coverage_population(&relative);
        match population.get(&path) {
            None => violations.push(format!("{relative}: no module declaration reaches it")),
            Some(true) if counted => {
                violations.push(format!("{relative}: builds only for tests, but is counted"));
            }
            Some(false) if !counted => {
                violations.push(format!(
                    "{relative}: builds for production, but is left out"
                ));
            }
            Some(_) => {}
        }
    }

    assert!(
        violations.is_empty(),
        "the coverage population and the production build must hold the same files:\n{}",
        violations.join("\n")
    );
    Ok(())
}

/// coverage taskが外すpathの正規表現。
fn ignore_filename_regex(manifest: &str) -> Result<&str, String> {
    let declared = manifest
        .lines()
        .find(|line| line.contains("--ignore-filename-regex"))
        .ok_or_else(|| "mise.toml leaves out no path from coverage".to_string())?;
    // 正規表現は`'`を含まないため、行はちょうど3つに割れる。割れ方が変わったなら、
    // 引用の形が変わっている。
    let quoted: Vec<&str> = declared.split('\'').collect();
    match quoted.as_slice() {
        [_, pattern, _] => Ok(pattern),
        _ => Err(format!(
            "--ignore-filename-regex must carry one quoted pattern: {declared}"
        )),
    }
}

/// 正規表現をtop-levelの`|`で割る。
///
/// `(^|/)`の`|`は選択肢の区切りではない。group、文字class、escapeの中では割らない。
fn alternatives(pattern: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    let mut in_class = false;
    let mut escaped = false;
    for character in pattern.chars() {
        if escaped {
            current.push(character);
            escaped = false;
            continue;
        }
        match character {
            '\\' => {
                current.push(character);
                escaped = true;
            }
            '[' if !in_class => {
                in_class = true;
                current.push(character);
            }
            ']' if in_class => {
                in_class = false;
                current.push(character);
            }
            '(' if !in_class => {
                depth += 1;
                current.push(character);
            }
            ')' if !in_class => {
                depth = depth.saturating_sub(1);
                current.push(character);
            }
            '|' if !in_class && depth == 0 => parts.push(std::mem::take(&mut current)),
            _ => current.push(character),
        }
    }
    parts.push(current);
    parts
}

/// coverage taskが外すのは、規約が定めた4か所だけか。
///
/// 足りないほうだけを見ると、除外を1つ足して本番codeを母集団から外せる。数も綴りも
/// 一致することを求める。
#[test]
fn the_coverage_task_leaves_out_the_same_places() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("mise.toml"))?;

    let mut declared = alternatives(ignore_filename_regex(&manifest)?);
    declared.sort();
    let mut expected: Vec<String> = OUTSIDE_THE_COVERAGE_POPULATION
        .iter()
        .map(|(_, pattern)| (*pattern).to_string())
        .collect();
    expected.sort();

    assert_eq!(
        declared, expected,
        "the coverage task must leave out exactly the places test support may live"
    );
    Ok(())
}

/// coverage taskがcargo-llvm-covへ渡す語。
///
/// `run`の中身は行末の`\`で続く1つのcommandである。語へ割ってから読むことで、
/// `--fail-under-lines`と`--fail-under-file-lines`のように互いに似た綴りを取り違えない。
fn coverage_task_words(manifest: &str) -> Result<Vec<String>, String> {
    let declared = manifest
        .split_once("[tasks.coverage]")
        .ok_or_else(|| "mise.toml declares no coverage task".to_string())?
        .1;
    let opened = declared
        .split_once("'''")
        .ok_or_else(|| "the coverage task has no run block".to_string())?
        .1;
    let body = opened
        .split_once("'''")
        .ok_or_else(|| "the run block of the coverage task does not end".to_string())?
        .0;
    Ok(body
        .split_whitespace()
        .filter(|word| *word != "\\")
        .map(str::to_string)
        .collect())
}

/// optionがちょうど1度渡され、その値が下限を下回らないか。
///
/// cargo-llvm-covは同じoptionを2度渡すと後ろを採る。綴りが在ることだけを見ると、後ろへ
/// 緩い値を足して基準を無効にできる。回数と値の両方を求める。
fn a_floor_of(words: &[String], option: &str, least: f64) -> Result<(), String> {
    let passed: Vec<&String> = words
        .iter()
        .enumerate()
        .filter(|(_, word)| word.as_str() == option)
        .filter_map(|(index, _)| words.get(index + 1))
        .collect();
    match passed.as_slice() {
        [] => Err(format!("the coverage task must pass {option}")),
        [value] => {
            let observed: f64 = value
                .parse()
                .map_err(|_| format!("{option} takes a percentage, not {value}"))?;
            if observed < least {
                return Err(format!(
                    "{option} must not fall below {least}; it passes {observed}"
                ));
            }
            Ok(())
        }
        many => Err(format!(
            "{option} is passed {} times; only the last one would decide",
            many.len()
        )),
    }
}

/// coverage taskが1 fileずつに求める行coverage。
///
/// 全体比率は、よくtestされたfileの行で別fileの未到達行を相殺できる。file別floorはその
/// 相殺を止めるために在り、下げれば止まらなくなる。値の引き下げも、同じoptionを後ろへ
/// 書いての上書きも落とす。母集団から外してよいpathは
/// `the_coverage_task_leaves_out_the_same_places`が別に固定する。
#[test]
fn every_counted_file_answers_for_eighty_percent_of_its_own_lines()
-> Result<(), Box<dyn std::error::Error>> {
    let manifest = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("mise.toml"))?;
    a_floor_of(
        &coverage_task_words(&manifest)?,
        "--fail-under-file-lines",
        80.0,
    )?;
    Ok(())
}

/// 全体の最低基準は、file別floorを入れても下げない。
///
/// file別floorは相殺を止めるだけで、80%を超えたfileの劣化までは止めない。両方を課す。
#[test]
fn the_overall_floors_stay_where_they_are() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("mise.toml"))?;
    let words = coverage_task_words(&manifest)?;
    for (option, least) in [
        ("--fail-under-lines", 90.0),
        ("--fail-under-functions", 90.0),
        ("--fail-under-regions", 88.0),
    ] {
        a_floor_of(&words, option, least)?;
    }
    Ok(())
}

/// item名をfile stemへ写す。
///
/// `CamelCase`と`SCREAMING_SNAKE_CASE`の両方を同じ規則で扱う。語の境界は、小文字か
/// 数字のあとの大文字と、大文字が続いたあとに小文字が始まる位置だけとする。既にある
/// `_`は境界そのものなので、そこへ重ねて`_`を足さない。
fn snake_case(name: &str) -> String {
    let characters: Vec<char> = name.chars().collect();
    let mut result = String::with_capacity(name.len());
    for (index, &character) in characters.iter().enumerate() {
        if character == '_' {
            result.push('_');
            continue;
        }
        let previous = index.checked_sub(1).map(|before| characters[before]);
        let boundary = character.is_ascii_uppercase()
            && match previous {
                None | Some('_') => false,
                // 略語の途中は切らない。`SSH_CLONE`は`ssh_clone`、`ProjectId`は`project_id`。
                Some(before) if before.is_ascii_uppercase() => characters
                    .get(index + 1)
                    .is_some_and(char::is_ascii_lowercase),
                Some(_) => true,
            };
        if boundary {
            result.push('_');
        }
        result.push(character.to_ascii_lowercase());
    }
    result
}

#[test]
fn a_known_macro_subject_is_counted() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! error_ids {
            () => { pub enum ErrorId { One } };
        }
        error_ids! {}
        ",
    )?;
    let source = Source {
        relative: "src/error_id.rs".to_string(),
        path: PathBuf::from("error_id.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert!(
        violations.is_empty(),
        "unexpected violations: {violations:?}"
    );
    Ok(())
}

#[test]
fn a_macro_subject_cannot_hide_another_public_subject() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! error_ids {
            () => { pub enum ErrorId { One } };
        }
        error_ids! {}
        pub fn error_id() {}
        ",
    )?;
    let source = Source {
        relative: "src/error_id.rs".to_string(),
        path: PathBuf::from("error_id.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert_eq!(violations.len(), 1);
    assert!(violations[0].contains("ErrorId, error_id"));
    Ok(())
}

#[test]
fn an_unknown_public_macro_is_not_silently_ignored() -> Result<(), syn::Error> {
    let syntax = syn::parse_file("make_public!();")?;
    let source = Source {
        relative: "src/make_public.rs".to_string(),
        path: PathBuf::from("make_public.rs"),
        syntax,
    };
    let mut violations = Vec::new();

    check_source(&source, &mut violations);

    assert_eq!(violations.len(), 1);
    assert!(violations[0].contains("make_public"));
    Ok(())
}

#[test]
fn a_compound_condition_that_needs_the_test_build_is_test_only() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r#"
        #[cfg(all(test, unix))]
        fn only_on_unix_tests() {}
        #[cfg(test)]
        #[cfg(target_os = "macos")]
        fn only_on_macos_tests() {}
        "#,
    )?;

    for item in &syntax.items {
        assert_eq!(gate(item_attributes(item)), Gate::TestOnly);
    }
    Ok(())
}

#[test]
fn a_condition_the_test_build_only_shares_decides_nothing() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        #[cfg(any(test, unix))]
        fn also_on_unix() {}
        #[cfg(not(test))]
        fn never_in_tests() {}
        #[cfg(unix)]
        fn no_word_about_tests() {}
        ",
    )?;
    let gates: Vec<Gate> = syntax
        .items
        .iter()
        .map(|i| gate(item_attributes(i)))
        .collect();

    assert_eq!(
        gates,
        [Gate::Undecidable, Gate::ProductionOnly, Gate::Unconditional]
    );
    Ok(())
}

#[test]
fn a_test_only_item_beside_its_subject_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        pub struct Ui;
        impl Ui {
            #[cfg(test)]
            pub fn capture() -> Ui { Ui }
        }
        #[cfg(test)]
        #[path = 'ui_test.rs']
        mod ui_test;
        "
        .replace('\'', "\"")
        .as_str(),
    )?;
    let mut counted = CountedFile {
        relative: "src/design/ui.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("an associated item"));
    Ok(())
}

#[test]
fn a_macro_that_builds_test_only_items_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! error_ids {
            () => {
                impl ErrorId {
                    #[cfg(test)]
                    pub const ALL: &'static [ErrorId] = &[];
                }
            };
        }
        ",
    )?;
    let mut counted = CountedFile {
        relative: "src/diagnostics/error_id.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("error_ids"));
    Ok(())
}

#[test]
fn a_production_only_associated_item_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        pub struct Request;
        impl Request {
            #[cfg(not(test))]
            pub fn production_only(&self) {}
        }
        ",
    )?;
    let mut sharing = SharedDecision {
        relative: "src/request.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
    };

    sharing.visit_file(&syntax);

    assert_eq!(sharing.violations.len(), 1);
    assert!(sharing.violations[0].contains("associated item"));
    Ok(())
}

#[test]
fn a_compound_condition_in_a_macro_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! test_helper {
            () => {
                #[cfg(all(test, unix))]
                pub fn helper() {}
            };
        }
        impl Request {
            test_helper!();
        }
        ",
    )?;
    let mut counted = CountedFile {
        relative: "src/request.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("test_helper"));
    Ok(())
}

#[test]
fn a_test_only_cfg_attr_in_a_macro_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        macro_rules! test_helper {
            () => {
                #[cfg_attr(test, derive(Default))]
                pub struct Request;
            };
        }
        ",
    )?;
    let mut counted = CountedFile {
        relative: "src/request.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("test_helper"));
    Ok(())
}

#[test]
fn a_test_only_expression_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        fn production_function() {
            #[cfg(test)]
            std::hint::black_box(());
        }
        ",
    )?;
    let mut counted = CountedFile {
        relative: "src/request.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("fn production_function"));
    Ok(())
}

#[test]
fn an_attribute_that_only_test_builds_apply_is_reported() -> Result<(), syn::Error> {
    let syntax = syn::parse_file(
        r"
        #[cfg_attr(test, derive(Default))]
        pub struct Request;
        ",
    )?;
    let mut counted = CountedFile {
        relative: "src/commands/add/request.rs",
        violations: Vec::new(),
        context: "an item".to_string(),
        policy: AttributePolicy::CountedCode,
    };

    counted.visit_file(&syntax);

    assert_eq!(counted.violations.len(), 1);
    assert!(counted.violations[0].contains("only in test builds"));
    Ok(())
}

#[test]
fn a_group_does_not_end_an_alternative() {
    assert_eq!(
        alternatives("(^|/)tests/|[^/]*_test[^/]*\\.rs$"),
        ["(^|/)tests/", "[^/]*_test[^/]*\\.rs$"]
    );
}
